### ISSUE TITLE
[Issue]: The app crashes when rating an app

### ISSUE THREAD

**Issue by GrafKiedyOdcinek** [techlore/Plexus-app#40]
### Description

The app crashes when rating an app that doesn't have any other ratings. For some apps the rating isn't submitted and when I try to submit the rating again it says that I don't have a de-Googled/MicroG device. I'm using CalyxOS on Pixel 6.

### Steps to reproduce the issue

The app crashes when I submit a rating for the app Max (and other apps without ratings)
The app doesn't submit a rating when I rate the game The Simpsons: Tapped Out (and other apps without ratings).

### Device

Both de-Googled & microG

### Terms

- [X] This issue occurs on the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another issue.

**Comment by StellarSand** [comment]
There's a lot of ratings from CalyxOS in our database, so the app is working fine on it. There's also many apps that have ratings only from CalyxOS, further confirming the fact that the app works when rating a previous unrated app on CalyxOS.
Here's a few examples of apps which have ratings only from CalyxOS:

<img src="https://github.com/user-attachments/assets/8f60d6fb-ddd2-4e59-b0d1-f783ca2b3017" width=200> <img src="https://github.com/user-attachments/assets/4a06a6d0-2044-4ba7-b427-8ea4fa918c60" width=200> <img src="https://github.com/user-attachments/assets/06fe354b-ae5c-4be4-8676-0ba4be0b8b72" width=200>

<img src="https://github.com/user-attachments/assets/2fc1ddfc-8442-4569-aa69-138384aa2525" width=200> <img src="https://github.com/user-attachments/assets/47e93b23-3d1a-44e0-82a6-529db1f6e8ea" width=200> <img src="https://github.com/user-attachments/assets/e39e8563-38cd-42b1-bba7-7df5dd1b2fe7" width=200>

<img src="https://github.com/user-attachments/assets/357468a8-457b-4bd5-ab55-be86381cb869" width=200> <img src="https://github.com/user-attachments/assets/97edca5d-2e44-42b7-9ea8-37d3c3c6e408" width=200>

You can try the following steps:
- Make sure you're on the [latest version of the app](https://github.com/techlore/Plexus-app/releases/latest) (not from F-Droid).
- Clear the storage data & cache (or alternatively uninstall & install the app again).
- If the app still crashes for you, upload the [crash logs](https://developer.android.com/studio/debug/bug-report).

**Comment by GrafKiedyOdcinek** [comment]
I reinstalled the app using the latest version from GitHub and I still experience the same issue.
That YouTube Studio rating is actually from my device, which is very weird, becouse I can't submit ratings for apps without other ratings (after a few days I could submit ratings for more apps, becouse they received ratings from others when previously it wouldn't submit them).
Could you give me more instructions on how I can create and share the logs? I don't understand the insturctions that you provided.

**Comment by StellarSand** [comment]
- Download [platform tools](https://developer.android.com/tools/releases/platform-tools#downloads) & extract it.
- In your phone's settings enable developer options. After enabling it go to developer options (most probably in `System > Developer options`) and enable `USB Debugging`.
- Connect phone to laptop/PC.
- Open cmd (if on windows) or terminal.
- Change directory to the extracted `platform-tools` folder:
  - Windows:
    ```
    cd C:\path\to\platform-tools
    ```
  - Linux/macOS:
    ```
    cd /path/to/platform-tools
    ```
- Check if device is detected using adb:
  ```
  adb devices
  ```
  You may see a prompt on your phone asking you to allow USB debugging. Accept it to proceed.
- Open the Plexus app and make it crash once.
- Get logs:
  ```
  adb logcat -d > logcat.txt
  ```
  The `logcat.txt` file will be located inside the extracted platform-tools folder.
- Upload the file here (or search for `plexus` in the file and copy paste everything from there).

**Comment by GrafKiedyOdcinek** [comment]
I fixed the issue by disabling my dns. After looking at the logs it looks like if play.google.com is blocked the app crashes. I think it should show a message that play.google.com is blocked and for the application to fully work you need to unlock it, instead of the app just crashing.
Here are the logs:
FATAL EXCEPTION: main
Process: tech.techlore.plexus, PID: 2200
java.net.ConnectException: Failed to connect to play.google.com/0.0.0.0:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:848)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:818)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:346)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:331)
	at tech.techlore.plexus.fragments.bottomsheets.submit.SubmitBottomSheet$getIconUrl$3.invokeSuspend(SubmitBottomSheet.kt:271)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bacc8f4, Dispatchers.Main.immediate]

**Comment by StellarSand** [comment]
So this happens because the icons are retrieved from play.google.com. Instead of showing a message, I may have some other ideas which could fix it & blocking from DNS will continue to function normally. Thanks for sharing the crash logs.
