### ISSUE TITLE
[Issue]: Crash upon invocation.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [techlore/Plexus-app#42]
### Description

I invoked https://apt.izzysoft.de/fdroid/repo/tech.techlore.plexus_206.apk, and it crashed.

### Steps to reproduce the issue

1. Install https://apt.izzysoft.de/fdroid/repo/tech.techlore.plexus_206.apk.
2. Invoke it.

### Device

Google Play Services

### Error messages/logs

<blockQuote>

```log
FATAL EXCEPTION: main
Process: tech.techlore.plexus, PID: 16894
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@241406a, Dispatchers.Main.immediate]
```

</blockQuote>

### Additional context

May relate to https://github.com/techlore/Plexus-app/issues/18#issuecomment-2195171145.

### Terms

- [X] This issue occurs on the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another issue.

**Comment by StellarSand** [comment]
This might be due to slow internet, high traffic on our servers, or other network issues.
I tested on both: an emulator & a physical device, & it is not reproducible on my end:

https://github.com/user-attachments/assets/3aec64c9-9865-4f7a-bd66-4bc4bce8411e

You can try checking your internet connection or switch to a different network, if possible. Maybe I'll also increase the default timeout value to 30 seconds, which should help a bit with some slow networks.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/techlore/Plexus-app/issues/42#issuecomment-2325235071

@StellarSand, doesn't appear to be reproducible for me either. Was just quite confusing when I invoked the application. Want me to close the issue thus?

**Comment by StellarSand** [comment]
It very well could be due to high traffic on our servers. Is the app working fine for you now?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/techlore/Plexus-app/issues/42#issuecomment-2325259949

Yes, although it's noticeably slow to load, initially.

**Comment by StellarSand** [comment]
Hmm, will need to check with Tom to see if there are any slowdowns.

**Comment by StellarSand** [comment]
Please try the latest version.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/techlore/Plexus-app/issues/42#issuecomment-2361374705

@StellarSand, https://github.com/techlore/Plexus-app/releases/download/v2.0.7/Plexus_v2.0.7.apk does seem to work.

**Comment by RokeJulianLockhart** [comment]
Though, the last time I tried https://github.com/techlore/Plexus-app/releases/download/v2.0.6/Plexus_v2.0.6.apk, I actually got a different log:

```log
FATAL EXCEPTION: main
Process: tech.techlore.plexus, PID: 10735
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "updated_at" (class tech.techlore.plexus.models.get.apps.GetApp), not marked as ignorable (4 known properties: "icon_url", "name", "package", "scores"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 298] (through reference chain: tech.techlore.plexus.models.get.apps.GetAppsRoot["data"]->java.util.ArrayList[0]->tech.techlore.plexus.models.get.apps.GetApp["updated_at"])
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1153)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2241)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1793)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1743)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:576)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:446)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2125)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1501)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:246)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:156)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e978bf1, Dispatchers.Main.immediate]

```

**Comment by StellarSand** [comment]
Yes the crash log you shared from v2.0.6 is because there were some changes made in our API. Specifically if you see the line `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "updated_at"`
We added a new field `updated_at` and all previous versions will crash because of this.
