### ISSUE TITLE
[Issue]: Crashes when scanning installed apps

### ISSUE THREAD

**Issue by Zumux** [techlore/Plexus-app#43]
### Description

The app crashes right after it shows "Scanning installed apps" on startup. It does this with both the fdroid version and the one from github. 

### Steps to reproduce the issue

1. Launch the app
2. Wait for it to say "Scanning installed apps"
3. Crashes

### Device

de-Googled

### Error messages/logs

```
type: crash
osVersion: google/bluejay/bluejay:14/AP2A.240805.005.F1/2024082200:user/release-keys
package: tech.techlore.plexus:206
process: tech.techlore.plexus
processUptime: 3319 + 277 ms
installer: com.android.packageinstaller

android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:522)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:499)
	at tech.techlore.plexus.utils.SystemUtils$Companion.getAppInfo(SystemUtils.kt:60)
	at tech.techlore.plexus.utils.SystemUtils$Companion.isDeviceDeGoogledOrMicroG(SystemUtils.kt:49)
	at tech.techlore.plexus.activities.SplashActivity$retrieveData$1.invokeSuspend(SplashActivity.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c1cf9f2, Dispatchers.Main.immediate]

```

### Additional context

App version: 2.0.6 (From fdroid and github)
OS: GrapheneOS 14 2024082200

### Terms

- [X] This issue occurs on the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another issue.

**Comment by StellarSand** [comment]
This may be fixed by [ad115e4](https://github.com/techlore/Plexus-app/commit/ad115e4e0b340b29e8037e3f6231aabeb1f89500). If the issue persists in the next release, feel free to reopen the issue.
