### ISSUE TITLE
[Announcement]: API changes results in app crashing

### ISSUE THREAD

**Issue by StellarSand** [techlore/Plexus-app#45]
### Description

Some changes were made in our API which results in the app crashing on launch. Please wait for a new release in a couple days.

### Steps to reproduce the issue

1. Launch app.
2. App crashes.

### Device

Both de-Googled & microG

### Terms

- [X] This issue occurs on the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another issue.

**Comment by StellarSand** [comment]
Fixed with [v2.0.7](https://github.com/techlore/Plexus-app/releases/latest)

**Comment by xronin01** [comment]
FATAL EXCEPTION: main
Process: tech.techlore.plexus, PID: 22996
java.lang.NullPointerException: versionName must not be null
	at tech.techlore.plexus.utils.PackageUtils$Companion$scannedInstalledAppsList$2.invokeSuspend(PackageUtils.kt:75)
	at tech.techlore.plexus.utils.PackageUtils$Companion$scannedInstalledAppsList$2.invoke(Unknown Source:8)
	at tech.techlore.plexus.utils.PackageUtils$Companion$scannedInstalledAppsList$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at tech.techlore.plexus.utils.PackageUtils$Companion.scannedInstalledAppsList(PackageUtils.kt:35)
	at tech.techlore.plexus.repositories.database.MainDataRepository$installedAppsIntoDB$2.invokeSuspend(MainDataRepository.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b98b721, Dispatchers.Main.immediate]

**Comment by xronin01** [comment]
Crash 2.0.7
